//===========================================================
// C#
//
// Error code constant definition module for ymcPACPI.Dll ÅÉymcErrorCode.csÅÑ
//
// Version (date)		ÅF  Ver.1.0.0.0 (12/02/27)
//
// Remarks              ÅF	
//
//===========================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

namespace MotionYMC
{
	public partial class CMotionAPI
	{
	    public const UInt32 MP_SUCCESS                          = 0x00000000;	/* API function normal completion                      */
	    public const UInt32 MP_FAIL 							= 0x4000FFFF;   /* API function erroneous completion                   */
	    public const UInt32 WDT_OVER_ERR 						= 0x81000001;   /*                                                     */
	    public const UInt32 MANUAL_RESET_ERR 					= 0x82000020;   /* Manual reset error                                  */
	    public const UInt32 TLB_MLTHIT_ERR 						= 0x82000140;   /* TLB multi hit error                                 */
	    public const UInt32 UBRK_ERR 							= 0x820001E0;   /* User break execution error                          */
	    public const UInt32 ADR_RD_ERR 							= 0x820000E0;   /* Address read error error                            */
	    public const UInt32 TLB_MIS_RD_ERR 						= 0x82000040;   /* TLB read mis error                                  */
	    public const UInt32 TLB_PROTECTION_RD_ERR 				= 0x820000A0;   /* TLB protection read vaiolation error                */
	    public const UInt32 GENERAL_INVALID_INS_ERR 			= 0x82000180;   /* General invalid instruction error                   */
	    public const UInt32 SLOT_ERR 							= 0x820001A0;   /* Slot invalid instruction error                      */
	    public const UInt32 GENERAL_FPU_DISABLE_ERR 			= 0x82000800;   /* General FPU disable error                           */
	    public const UInt32 SLOT_FPU_ERR 						= 0x82000820;   /* Slot FPU exception error                            */
	    public const UInt32 ADR_WR_ERR 							= 0x82000100;   /* Data address write error error                      */
	    public const UInt32 TLB_MIS_WR_ERR 						= 0x82000060;   /* TLB write mis error                                 */
	    public const UInt32 TLB_PROTECTION_WR_ERR 				= 0x820000C0;   /* TLB protection write vaiolation error               */
	    public const UInt32 FPU_EXP_ERR 						= 0x82000120;   /* FPU exception error                                 */
	    public const UInt32 INITIAL_PAGE_EXP_ERR 				= 0x82000080;   /* Initial page write exception error                  */
	    public const UInt32 ROM_ERR 							= 0x81000041;   /* ROM  error                                          */
	    public const UInt32 RAM_ERR 							= 0x81000042;   /* RAM  error                                          */
	    public const UInt32 MPU_ERR 							= 0x81000043;   /* CPU  error                                          */
	    public const UInt32 FPU_ERR 							= 0x81000044;   /* FPU  error                                          */
	    public const UInt32 CERF_ERR 							= 0x81000049;   /* CERF error                                          */
	    public const UInt32 EXIO_ERR 							= 0x81000050;   /* EXIO error                                          */
	    public const UInt32 BUSIF_ERR 							= 0x8100005F;   /* Common RAM error for OEM                            */
	    public const UInt32 ALM_NO_ALM 							= 0x00000000;   /* No alarm                                                                                            */
	    public const UInt32 ALM_MK_DEBUG 						= 0x67050300;   /* Minor failure: Alarm code for debugging                                                             */
	    public const UInt32 ALM_MK_ROUND_ERR 					= 0x67050301;   /* Minor failure: Improper specification of one cycle at radius specification                          */
	    public const UInt32 ALM_MK_FSPEED_OVER 					= 0x67050302;   /* Minor failure: Feeding speed exceeded                                                               */
	    public const UInt32 ALM_MK_FSPEED_NOSPEC 				= 0x67050303;   /* Minor failure: Feeding speed not specified                                                          */
	    public const UInt32 ALM_MK_PRM_OVER 					= 0x67050304;   /* Minor failure: Value after conversion of acceleration or deceleration parameter is out of range.    */
	    public const UInt32 ALM_MK_ARCLEN_OVER 					= 0x67050305;   /* Minor failure: Arc length exceeds LONG_MAX.                                                         */
	    public const UInt32 ALM_MK_VERT_NOSPEC 					= 0x67050306;   /* Minor failure: Vertical axis by plane specification not specified                                   */
	    public const UInt32 ALM_MK_HORZ_NOSPEC 					= 0x67050307;   /* Minor failure: Horizontal axis by plane specification not specified                                 */
	    public const UInt32 ALM_MK_TURN_OVER 					= 0x67050308;   /* Minor failure: Specified number of turns exceeded                                                   */
	    public const UInt32 ALM_MK_RADIUS_OVER 					= 0x67050309;   /* Minor failure: Radius exceeds LONG_MAX.                                                             */
	    public const UInt32 ALM_MK_CENTER_ERR 					= 0x6705030A;   /* Minor failure: Illegal center point specification                                                   */
	    public const UInt32 ALM_MK_BLOCK_OVER 					= 0x6705030B;   /* Minor failure: Linear interpolation block moving amount exceeded                                    */
	    public const UInt32 ALM_MK_MAXF_NOSPEC 					= 0x6705030C;   /* Minor failure: maxf not defined                                                                     */
	    public const UInt32 ALM_MK_TDATA_ERR 					= 0x6705030D;   /* Minor failure: Address T data error                                                                 */
	    public const UInt32 ALM_MK_REG_ERR 						= 0x6705030E;   /* Minor failure: REG data error and PP fault                                                          */
	    public const UInt32 ALM_MK_COMMAND_CODE_ERR 			= 0x6705030F;   /* Minor failure: Out-of-range command                                                                 */
	    public const UInt32 ALM_MK_AXIS_CONFLICT 				= 0x67050310;   /* Minor failure: Use of logical axis being prohibited                                                 */
	    public const UInt32 ALM_MK_POSMAX_OVER 					= 0x67050311;   /* Minor failure: Infinite length axis, MVM or ABS coordinate designation exceeds POSMAX.              */
	    public const UInt32 ALM_MK_DIST_OVER 					= 0x67050312;   /* Minor failure: Axis moving distance is other than (LONG_MIN, LONG_MAX).                             */
	    public const UInt32 ALM_MK_MODE_ERR 					= 0x67050313;   /* Minor failure: Illegal control mode                                                                 */
	    public const UInt32 ALM_MK_CMD_CONFLICT 				= 0x67050314;   /* Minor failure: Motion command overlapping instruction                                               */
	    public const UInt32 ALM_MK_RCMD_CONFLICT 				= 0x67050315;   /* Minor failure: Motion response command overlapping instruction                                      */
	    public const UInt32 ALM_MK_CMD_MODE_ERR 				= 0x67050316;   /* Minor failure: Illegal motion command mode                                                          */
	    public const UInt32 ALM_MK_CMD_NOT_ALLOW 				= 0x67050317;   /* Minor failure: Command cannot be executed ih this Module.                                           */
	    public const UInt32 ALM_MK_CMD_DEN_FAIL 				= 0x67050318;   /* Minor failure: Distribution is not completed.                                                       */
	    public const UInt32 ALM_MK_H_MOVE_ERR 					= 0x67050319;   /* Minor failure: Illegal hMove                                                                        */
	    public const UInt32 ALM_MK_MOVE_NOT_SUPPORT 			= 0x6705031A;   /* Minor failure: Non-supported Move defined                                                           */
	    public const UInt32 ALM_MK_EVENT_NOT_SUPPORT 			= 0x6705031B;   /* Minor failure: Non-supported Move Event defined                                                     */
	    public const UInt32 ALM_MK_ACTION_NOT_SUPPORT 			= 0x6705031C;   /* Minor failure: Non-supported Move Action defined                                                    */
	    public const UInt32 ALM_MK_MOVE_TYPE_ERR 				= 0x6705031D;   /* Minor failure: MoveType specification error                                                         */
	    public const UInt32 ALM_MK_VTYPE_ERR 					= 0x6705031E;   /* Minor failure: VelocityType specification error                                                     */
	    public const UInt32 ALM_MK_ATYPE_ERR 					= 0x6705031F;   /* Minor failure: AccelerationType specification error                                                 */
	    public const UInt32 ALM_MK_HOMING_METHOD_ERR 			= 0x67050320;   /* Minor failure: Homing_method specification error                                                    */
	    public const UInt32 ALM_MK_ACC_ERR 						= 0x67050321;   /* Minor failure: Acceleration setting error                                                           */
	    public const UInt32 ALM_MK_DEC_ERR 						= 0x67050322;   /* Minor failure: Deceleration setting error                                                           */
	    public const UInt32 ALM_MK_POS_TYPE_ERR 				= 0x67050323;   /* Minor failure: Position reference type error                                                        */
	    public const UInt32 ALM_MK_INVALID_EVENT_ERR 			= 0x67050324;   /* Minor failure: Illegal EVENT type                                                                   */
	    public const UInt32 ALM_MK_INVALID_ACTION_ERR 			= 0x67050325;   /* Minor failure: Illegal ACTION type                                                                  */
	    public const UInt32 ALM_MK_MOVE_NOT_ACTIVE 				= 0x67050326;   /* Minor failure: Action for Move that has not been executed                                           */
	    public const UInt32 ALM_MK_MOVELIST_NOT_ACTIVE 			= 0x67050327;   /* Minor failure: Action for MoveList that has not been executed                                       */
	    public const UInt32 ALM_MK_TBL_INVALID_DATA 			= 0x67050328;   /* Minor failure: Illegal table data                                                                   */
	    public const UInt32 ALM_MK_TBL_INVALID_SEG_NUM 			= 0x67050329;   /* Minor failure: Illegal number of table interpolation execution segments                             */
	    public const UInt32 ALM_MK_TBL_INVALID_AXIS_NUM 		= 0x6705032A;   /* Minor failure: Illegal number of table interpolation axes specified                                 */
	    public const UInt32 ALM_MK_TBL_INVALID_ST_SEG 			= 0x6705032B;   /* Minor failure: Illegal table interpolation starting segment number                                  */
	    public const UInt32 ALM_MK_STBL_INVALID_EXE 			= 0x6705032C;   /* Minor failure: Execution error during Static table file being written                               */
	    public const UInt32 ALM_MK_DTBL_DUPLICATE_EXE 			= 0x6705032D;   /* Minor failure: Dynamic table duplicated execution error                                             */
	    public const UInt32 ALM_MK_LATCH_CONFLICT 				= 0x6705032E;   /* Minor failure: LATCH request overlapping instruction error                                          */
	    public const UInt32 ALM_MK_INVALID_AXISTYPE 			= 0x6705032F;   /* Minor failure: Illegal axis type (finite length axis/inifinite length axis)                         */
	    public const UInt32 ALM_MK_NOT_SVCRDY 					= 0x67050330;   /* Minor failure: Move object executed when Motion Driver operation is not ready                       */
	    public const UInt32 ALM_MK_NOT_SVCRUN 					= 0x67050331;   /* Minor failure: Move object executed at servo OFF                                                    */
	    public const UInt32 ALM_MK_MDALARM 						= 0x67050332;   /* Minor failure: Move object executed at occurrence of Motion Driver alarm                            */
	    public const UInt32 ALM_MK_SUPERPOSE_MASTER_ERR 		= 0x67050333;   /* Minor failure: Distribution synthetic object master axis condition error                            */
	    public const UInt32 ALM_MK_SUPERPOSE_SLAVE_ERR 			= 0x67050334;   /* Minor failure: Distribution synthetic object slave axis condition error                             */
	    public const UInt32 ALM_MK_MDWARNING 					= 0x57050335;   /* Warning: Motion Driver warning                                                                      */
	    public const UInt32 ALM_MK_MDWARNING_POSERR 			= 0x57050336;   /* Warning: Motion Driver deviation warning                                                            */
	    public const UInt32 ALM_MK_NOT_INFINITE_ABS 			= 0x67050337;   /* Minor failure: Specified axis cannot be used as ABS infinite length axis.                           */
	    public const UInt32 ALM_MK_INVALID_LOGICAL_NUM 			= 0x67050338;   /* Minor failure: Illegal logical axis number has been specified.                                      */
	    public const UInt32 ALM_MK_MAX_VELOCITY_ERR 			= 0x67050339;   /* Minor failure: Maximum speed setting error                                                          */
	    public const UInt32 ALM_MK_VELOCITY_ERR 				= 0x6705033A;   /* Minor failure: Speed setting error                                                                  */
	    public const UInt32 ALM_MK_APPROACH_ERR 				= 0x6705033B;   /* Minor failure: Approach speed setting error                                                         */
	    public const UInt32 ALM_MK_CREEP_ERR 					= 0x6705033C;   /* Minor failure: Creep speed setting error                                                            */
	    public const UInt32 ALM_MK_OS_ERR_MBOX1 				= 0x83050340;   /* Major failure: Mail box creation error (mail box for request for Motion Kernel Move object execution)*/
	    public const UInt32 ALM_MK_OS_ERR_MBOX2 				= 0x83050341;   /* Major failure: Mail box creation error (mail box for request for Motion Kernel action execution)    */
	    public const UInt32 ALM_MK_OS_ERR_SEND_MSG1 			= 0x83050342;   /* Major failure: Message sending error at OS level (MK to EM: Notification of event detection)        */
	    public const UInt32 ALM_MK_OS_ERR_SEND_MSG2 			= 0x83050343;   /* Major failure: Message sending error at OS level (MK to MM: Move completion message)                */
	    public const UInt32 ALM_MK_OS_ERR_SEND_MSG3 			= 0x83050344;   /* Major failure: Message sending error at OS level (EM to MM: Notification of Action)                 */
	    public const UInt32 ALM_MK_OS_ERR_SEND_MSG4 			= 0x83050345;   /* Major failure: Message sending error at OS level (Others)                                           */
	    public const UInt32 ALM_MK_ACTION_ERR1 					= 0x53050346;   /* Warning: Illegal response message received (action execution request to waiting status for response of notification of action execution completion) */
	    public const UInt32 ALM_MK_ACTION_ERR2 					= 0x53050347;   /* Warning: Illegal response message received(not an action for Move object currently executed)        */
	    public const UInt32 ALM_MK_ACTION_ERR3 					= 0x53050348;   /* Warning: Illegal response message received (not an action for MoveLIST object currently executed)   */
	    public const UInt32 ALM_MK_RCV_INV_MSG1 				= 0x53050349;   /* Warning: Illegal command message received (not a MOVE object handle)                                */
	    public const UInt32 ALM_MK_RCV_INV_MSG2 				= 0x5305034A;   /* Warning: Illegal command message received (command from other than Motion Manager)                  */
	    public const UInt32 ALM_MK_RCV_INV_MSG3 				= 0x5305034B;   /* Warning: Illegal command message received (not a command message)                                   */
	    public const UInt32 ALM_MK_RCV_INV_MSG4 				= 0x5305034C;   /* Warning: Illegal command message received (message other than command/response)                     */
	    public const UInt32 ALM_MK_RCV_INV_MSG5 				= 0x5305034D;   /* Warning: Illegal command message received (command message from other than Event Manager)           */
	    public const UInt32 ALM_MK_RCV_INV_MSG6 				= 0x5305034E;   /* Warning: Illegal command message received (command message other than request for action execution) */
	    public const UInt32 ALM_MK_RCV_INV_MSG7 				= 0x5305034F;   /* Warning: Illegal response message received (response message from other than Event Manager)         */
	    public const UInt32 ALM_MK_RCV_INV_MSG8 				= 0x53050350;   /* Warning: Illegal response message received (response message other than event notification completion/action completion notification)   */
	    public const UInt32 ALM_MK_AXIS_HANDLE_ERROR 			= 0x67050360;   /* Minor failure: Axis handle number is incorrect.                                                     */
	    public const UInt32 ALM_MK_SLAVE_USED_AS_MASTER 		= 0x67050361;   /* Minor failure: An attempt was made to use a slave axis as a master axis.                            */
	    public const UInt32 ALM_MK_MASTER_USED_AS_SLAVE 		= 0x67050362;   /* Minor failure: An attempt was made to use a master axis as a slave axis.                            */
	    public const UInt32 ALM_MK_SLAVE_HAS_2_MASTERS 			= 0x67050363;   /* Minor failure: More than two master axes were specified for the same slave axis.                    */
	    public const UInt32 ALM_MK_SLAVE_HAS_NOT_WORK 			= 0x67050364;   /* Minor failure: Work axis cannot be assured for a slave axis.                                        */
	    public const UInt32 ALM_MK_PARAM_OUT_OF_RANGE 			= 0x67050365;   /* Minor failure: Parameter is out of range.                                                           */
	    public const UInt32 ALM_MK_NNUM_MAX_OVER 				= 0x67050366;   /* Minor failure: Maximum number of averaging times exceeded                                           */
	    public const UInt32 ALM_MK_FGNTBL_INVALID 				= 0x67050367;   /* Minor failure: Contents of the FGN table are illegal.                                               */
	    public const UInt32 ALM_MK_PARAM_OVERFLOW 				= 0x67050368;   /* Minor failure: Set value overflows.                                                                 */
	    public const UInt32 ALM_MK_ALREADY_COMMANDED 			= 0x67050369;   /* Minor failure: CAM or GEAR has already been under execution.                                        */
	    public const UInt32 ALM_MK_MULTIPLE_SHIFTS 				= 0x6705036A;   /* Minor failure: Position Offset/Cam Shift was executed during execution of Position Offset/Cam Shift.*/
	    public const UInt32 ALM_MK_CAMTBL_INVALID 				= 0x6705036B;   /* Minor failure: CAM table is illegal (address, contents, etc.).                                      */
	    public const UInt32 ALM_MK_ABORTED_BY_STOPMTN 			= 0x6705036C;   /* Minor failure: CAM/GEAR is aborted by STOP MOTION, etc.                                             */
	    public const UInt32 ALM_MK_HMETHOD_INVALID 				= 0x6705036D;   /* Minor failure: Non-supported zero point return method                                               */
	    public const UInt32 ALM_MK_MASTER_INVALID 				= 0x6705036E;   /* Minor failure: Master axis is not specified for monitoring.                                         */
	    public const UInt32 ALM_MK_DATA_HANDLE_INVALID 			= 0x6705036F;   /* Minor failure: Register/global data handle is illegal.                                              */
	    public const UInt32 ALM_MK_UNKNOWN_CAM_GEAR_ERR 		= 0x67050370;   /* Minor failure: Unclear error related to CAM/GEAR                                                    */
	    public const UInt32 ALM_MK_REG_SIZE_INVALID 			= 0x67050371;   /* Minor failure: Register handle size is illegal.                                                     */
	    public const UInt32 ALM_MK_ACTION_HANDLE_ERROR 			= 0x67050372;   /* Minor failure: Action handle is illegal.                                                            */
	    public const UInt32 ALM_MM_OS_ERR_MBOX1 				= 0x83040380;   /* Major failure: Mail box creation error (mail box to start up Motion Manager)                        */
	    public const UInt32 ALM_MM_OS_ERR_SEND_MSG1 			= 0x83040381;   /* Major failure: Message sending error at OS level (Motion Manager to Motion Kernel)                  */
	    public const UInt32 ALM_MM_OS_ERR_SEND_MSG2 			= 0x83040382;   /* Major failure: Message sending error at OS level (Motion Manager to Event Manager)                  */
	    public const UInt32 ALM_MM_OS_ERR_RCV_MSG1 				= 0x83040383;   /* Major failure: Message receiving error at OS level                                                  */
	    public const UInt32 ALM_MM_MK_BUSY 						= 0x67040384;   /* Minor failure: All Motion Kernels are in use.                                                       */
	    public const UInt32 ALM_MM_RCV_INV_MSG1 				= 0x53040385;   /* Warning: Illegal command message received (illegal handle 1: Not hMOVE.)                            */
	    public const UInt32 ALM_MM_RCV_INV_MSG2 				= 0x53040386;   /* Warning: Illegal command message received (illegal handle 2: hMOVE does not exist.)                 */
	    public const UInt32 ALM_MM_RCV_INV_MSG3 				= 0x53040387;   /* Warning: Illegal command message received (Not request for start action execution)                  */
	    public const UInt32 ALM_MM_RCV_INV_MSG4 				= 0x53040388;   /* Warning: Illegal response message received (response message other than event notification completion)  */
	    public const UInt32 ALM_MM_RCV_INV_MSG5 				= 0x53040389;   /* Warning: Illegal response message received (Other messages received with action completion response message)    */
	    public const UInt32 ALM_IM_DEVICEID_ERR 				= 0x53060480;   /* DeviceID error or non-supported Device              */
	    public const UInt32 ALM_IM_REGHANDLE_ERR 				= 0x53060481;   /* Register handle error                               */
	    public const UInt32 ALM_IM_GLOBALHANDLE_ERR 			= 0x53060482;   /* Global data handle error                            */
	    public const UInt32 ALM_IM_DEVICETYPE_ERR 				= 0x53060483;   /* Non-supported data type                             */
	    public const UInt32 ALM_IM_OFFSET_ERR 					= 0x53060484;   /* Incorrect offset value                              */
	    public const UInt32 AM_ER_UNDEF_COMMAND 				= 0x57020501;   /* Illegal command code                                */
	    public const UInt32 AM_ER_UNDEF_CMNDTYPE 				= 0x57020502;   /* Illegal command type                                */
	    public const UInt32 AM_ER_UNDEF_OBJTYPE 				= 0x57020503;   /* Illegal object type                                 */
	    public const UInt32 AM_ER_UNDEF_HANDLETYPE 				= 0x57020504;   /* Illegal handle type                                 */
	    public const UInt32 AM_ER_UNDEF_PKTDAT 					= 0x57020505;   /* Illegal packet data                                 */
	    public const UInt32 AM_ER_UNDEF_AXIS 					= 0x57020506;   /* axis not defined                                    */
	    public const UInt32 AM_ER_MSGBUF_GET_FAULT 				= 0x57020510;   /* Acquisition failure of  message buffer managed table*/
	    public const UInt32 AM_ER_ACTSIZE_GET_FAULT 			= 0x57020511;   /* Acquisition failure of ACT size                     */
	    public const UInt32 AM_ER_APIBUF_GET_FAULT 				= 0x57020512;   /* Acquisition failure of API buffer managed table     */
	    public const UInt32 AM_ER_MOVEOBJ_GET_FAULT 			= 0x57020513;   /* Acquisition failure of MOVE object managed table    */
	    public const UInt32 AM_ER_EVTTBL_GET_FAULT 				= 0x57020514;   /* Acquisition failure of event managed table          */
	    public const UInt32 AM_ER_ACTTBL_GET_FAULT 				= 0x57020515;   /* Acquisition failure of Action managed table         */
	    public const UInt32 AM_ER_1BY1APIBUF_GET_FAULT 			= 0x57020516;   /* Acquisition failure of Sequence managed table       */
	    public const UInt32 AM_ER_AXSTBL_GET_FAULT 				= 0x57020517;   /* Acquisition failure of AXIS handle managed table    */
	    public const UInt32 AM_ER_SUPERPOSEOBJ_GET_FAULT 		= 0x57020518;   /* Acquisition failure of Distribution synthetic object managed table  */
	    public const UInt32 AM_ER_SUPERPOSEOBJ_CLEAR_FAULT 		= 0x57020519;   /* Deletion failure of Distribution synthetic object   */
	    public const UInt32 AM_ER_AXIS_IN_USE 					= 0x5702051A;   /* axis in use                                         */
	    public const UInt32 AM_ER_HASHTBL_GET_FAULT 			= 0x5702051B;   /* Hash table acquisition failure for axial name management    */
	    public const UInt32 AM_ER_UNMATCH_OBJHNDL 				= 0x57020530;   /* MOVE object handle mismatched                       */
	    public const UInt32 AM_ER_UNMATCH_OBJECT 				= 0x57020531;   /* Object mismatched                                   */
	    public const UInt32 AM_ER_UNMATCH_APIBUF 				= 0x57020532;   /* API buffer mismatched                               */
	    public const UInt32 AM_ER_UNMATCH_MSGBUF 				= 0x57020533;   /* Message buffer mismatched                           */
	    public const UInt32 AM_ER_UNMATCH_ACTBUF 				= 0x57020534;   /* Action execution management buffer mismatched       */
	    public const UInt32 AM_ER_UNMATH_SEQUENCE 				= 0x57020535;   /* Sequence number mismatched                          */
	    public const UInt32 AM_ER_UNMATCH_1BY1APIBUF 			= 0x57020536;   /* Sequential API management table mismatched          */
	    public const UInt32 AM_ER_UNMATCH_MOVEOBJTABLE 			= 0x57020537;   /* MOVE object management table mismatched             */
	    public const UInt32 AM_ER_UNMATCH_MOVELISTTABLE 		= 0x57020538;   /* MOVE LIST management table mismatched               */
	    public const UInt32 AM_ER_UNMATCH_MOVELIST_OBJECT 		= 0x57020539;   /* MOVE LIST object mismatched                         */
	    public const UInt32 AM_ER_UNMATCH_MOVELIST_OBJHNDL 		= 0x5702053A;   /* MOVE LIST object handle mismatched                  */
	    public const UInt32 AM_ER_UNGET_MOVEOBJTABLE 			= 0x57020550;   /* MOVE object management table not assured            */
	    public const UInt32 AM_ER_UNGET_MOVELISTTABLE 			= 0x57020551;   /* MOVE LIST object management table not assured       */
	    public const UInt32 AM_ER_UNGET_1BY1APIBUFTABLE 		= 0x57020552;   /* Sequential API management table not assured         */
	    public const UInt32 AM_ER_NOEMPTYTBL_ERROR 				= 0x57020560;   /* No unused table among interpolation tables          */
	    public const UInt32 AM_ER_NOTGETSEM_ERROR 				= 0x57020561;   /* Failure to get AM-MK semaphore  (Dynamic)           */
	    public const UInt32 AM_ER_NOTGETTBLADD_ERROR 			= 0x57020562;   /* Failure to get interpolation table address          */
	    public const UInt32 AM_ER_NOTWRTTBL_ERROR 				= 0x57020563;   /* Failure to write in table at execution (Static)     */
	    public const UInt32 AM_ER_TBLINDEX_ERROR 				= 0x57020564;   /* Index setting error (Static)                        */
	    public const UInt32 AM_ER_ILLTBLTYPE_ERROR 				= 0x57020565;   /* Invalid table type specified                        */
	    public const UInt32 AM_ER_UNSUPORTED_EVENT 				= 0x57020570;   /* Event not supported or argument error               */
	    public const UInt32 AM_ER_WRONG_SEQUENCE 				= 0x57020571;   /* Sequence error                                      */
	    public const UInt32 AM_ER_MOVEOBJ_BUSY 					= 0x57020572;   /* MOVE object under execution                         */
	    public const UInt32 AM_ER_MOVELIST_BUSY 				= 0x57020573;   /* MOVE LIST under execution                           */
	    public const UInt32 AM_ER_MOVELIST_ADD_FAULT 			= 0x57020574;   /* MOVE OBJ cannot be registered.                      */
	    public const UInt32 AM_ER_CONFLICT_PHI_AXS 				= 0x57020575;   /* Physical axes overlapped                            */
	    public const UInt32 AM_ER_CONFLICT_LOG_AXS 				= 0x57020576;   /* Logic axes overlapped                               */
	    public const UInt32 AM_ER_PKTSTS_ERROR 					= 0x57020577;   /* Receiving packet status error                       */
	    public const UInt32 AM_ER_CONFLICT_NAME 				= 0x57020578;   /* Axis name overlapped                                */
	    public const UInt32 AM_ER_ILLEGAL_NAME 					= 0x57020579;   /* Incorrect axis name                                 */
	    public const UInt32 AM_ER_SEMAPHORE_ERROR 				= 0x5702057A;   /* Incorrect semaphore at host PC interruption         */
	    public const UInt32 AM_ER_LOG_AXS_OVER 					= 0x5702057B;   /* Logical axis number exceeded                        */
	    public const UInt32 IM_STATION_ERR 						= 0x55060B00;   /* Warning: Link communication station error           */
	    public const UInt32 IM_IO_ERR 							= 0x55060B01;   /* Warning: I/O error                                  */
	    public const UInt32 MP_FILE_ERR_GENERAL 				= 0x53168001;   /* General error.                                      */
	    public const UInt32 MP_FILE_ERR_NOT_SUPPORTED 			= 0x53168002;   /* Feature not supported.                              */
	    public const UInt32 MP_FILE_ERR_INVALID_ARGUMENT 		= 0x53168003;   /* Invalid argument                                    */
	    public const UInt32 MP_FILE_ERR_INVALID_HANDLE 			= 0x53168004;   /* Invalid handle                                      */
	    public const UInt32 MP_FILE_ERR_NO_FILE 				= 0x53168064;   /* No such file (or directory).                        */
	    public const UInt32 MP_FILE_ERR_INVALID_PATH 			= 0x53168065;   /* Invalid path.                                       */
	    public const UInt32 MP_FILE_ERR_EOF 					= 0x53168066;   /* End of file detected.                               */
	    public const UInt32 MP_FILE_ERR_PERMISSION_DENIED 		= 0x53168067;   /* Not arrowed to access the file.                     */
	    public const UInt32 MP_FILE_ERR_TOO_MANY_FILES 			= 0x53168068;   /* Too many files opened.                              */
	    public const UInt32 MP_FILE_ERR_FILE_BUSY 				= 0x53168069;   /* File is in use.                                     */
	    public const UInt32 MP_FILE_ERR_TIMEOUT 				= 0x5316806A;   /* Timeout occured.                                    */
	    public const UInt32 MP_FILE_ERR_BAD_FS 					= 0x531680C8;   /* Invalid or unexepected logical filesystem in the mediu
	    public const UInt32 MP_FILE_ERR_FILESYSTEM_FULL 		= 0x531680C9;   /* LFS (ie the media) is full.                         */
	    public const UInt32 MP_FILE_ERR_INVALID_LFM 			= 0x531680CA;   /* Invalid LFM specified.                              */
	    public const UInt32 MP_FILE_ERR_TOO_MANY_LFM 			= 0x531680CB;   /* LFM table is full.                                  */
	    public const UInt32 MP_FILE_ERR_INVALID_PDM 			= 0x5316812C;   /* Invalid PDM specified.                              */
	    public const UInt32 MP_FILE_ERR_INVALID_MEDIA 			= 0x5316812D;   /* Invalid media specified.                            */
	    public const UInt32 MP_FILE_ERR_TOO_MANY_PDM 			= 0x5316812E;   /* Too many PDM.                                       */
	    public const UInt32 MP_FILE_ERR_TOO_MANY_MEDIA 			= 0x5316812F;   /* Too many media.                                     */
	    public const UInt32 MP_FILE_ERR_WRITE_PROTECTED 		= 0x53168130;   /* Write protected media.                              */
	    public const UInt32 MP_FILE_ERR_INVALID_DEVICE 			= 0x53168190;   /* Invalid device specified.                           */
	    public const UInt32 MP_FILE_ERR_DEVICE_IO 				= 0x53168191;   /* Error occured in accessing the device.              */
	    public const UInt32 MP_FILE_ERR_DEVICE_BUSY 			= 0x53168192;   /* Device is in use.                                   */
	    public const UInt32 MP_FILE_ERR_NO_CARD 				= 0x5316A711;   /* CF CARD not mounted.                                */
	    public const UInt32 MP_FILE_ERR_CARD_POWER 				= 0x5316A712;   /* CF CARD Power-OFF.                                  */
	    public const UInt32 MP_CARD_SYSTEM_ERR 					= 0x53178FFF;   /* Card System Error.                                  */
	    public const UInt32 ERROR_CODE_GET_DIREC_OFFSET 		= 0x83001A01;   /* Directory area offset cannot be got.                */
	    public const UInt32 ERROR_CODE_GET_DIREC_INFO 			= 0x83001A02;   /* Directory area offset cannot be got.                */
	    public const UInt32 ERROR_CODE_FUNC_TABLE 				= 0x83001A03;   /* Failure to get directory information                */
	    public const UInt32 ERROR_CODE_SLEEP_TASK 				= 0x83001A04;   /* Failure to get system call function table           */
	    public const UInt32 ERROR_CODE_DEVICE_HANDLE_FULL 		= 0x43001A41;   /* Sleep error                                         */
	    public const UInt32 ERROR_CODE_ALLOC_MEMORY 			= 0x43001A42;   /* Number of device handles exceeds the maximum value. */
	    public const UInt32 ERROR_CODE_BUFCOPY 					= 0x43001A43;   /* Failure to get the area.                            */
	    public const UInt32 ERROR_CODE_GET_COMMEM_OFFSET 		= 0x43001A44;   /* MemoryCopy(),name_copy() error                      */
	    public const UInt32 ERROR_CODE_CREATE_SEMPH 			= 0x43001A45;   /* Failure to get common memory offset value           */
	    public const UInt32 ERROR_CODE_DELETE_SEMPH 			= 0x43001A46;   /* Semaphore creation error                            */
	    public const UInt32 ERROR_CODE_LOCK_SEMPH 				= 0x43001A47;   /* Semaphore deletion error                            */
	    public const UInt32 ERROR_CODE_UNLOCK_SEMPH 			= 0x43001A48;   /* Error at semaphore lock                             */
	    public const UInt32 ERROR_CODE_PACKETSIZE_OVER 			= 0x43001A49;   /* Error at semaphore release                          */
	    public const UInt32 ERROR_CODE_UNREADY                  = 0x43001A4A;   /*  Error when controller is being initialized         */
	    public const UInt32 ERROR_CODE_CPUSTOP                  = 0x43001A4B;   /*  Error when CPU is stopping                         */
	    public const UInt32 ERROR_CODE_CNTRNO                   = 0x470B1A81;   /*  CPU number is illegal                              */
	    public const UInt32 ERROR_CODE_SELECTION 				= 0x470B1A82;   /* Device number                                       */
	    public const UInt32 ERROR_CODE_LENGTH 					= 0x470B1A83;   /* Illegal selected value (0 or 1)                     */
	    public const UInt32 ERROR_CODE_OFFSET 					= 0x470B1A84;   /* Data length                                         */
	    public const UInt32 ERROR_CODE_DATACOUNT 				= 0x470B1A85;   /* Offset value                                        */
	    public const UInt32 ERROR_CODE_DATREAD 					= 0x46001A86;   /* Number of data items                                */
	    public const UInt32 ERROR_CODE_DATWRITE 				= 0x46001A87;   /* Failure to read out from common memory              */
	    public const UInt32 ERROR_CODE_BITWRITE 				= 0x46001A88;   /* Failure to write in to common memory                */
	    public const UInt32 ERROR_CODE_DEVCNTR 					= 0x46001A89;   /* Failure to write in bit data to common memory       */
	    public const UInt32 ERROR_CODE_NOTINIT 					= 0x460F1A8A;   /* DeviceIoControl() completed erroneously.            */
	    public const UInt32 ERROR_CODE_SEMPHLOCK 				= 0x41001A8B;   /* Driver initialization error                         */
	    public const UInt32 ERROR_CODE_SEMPHUNLOCK 				= 0x41001A8C;   /* Packet sending semaphore locked                     */
	    public const UInt32 ERROR_CODE_DRV_PROC 				= 0x460F1A8D;   /* Packet receiving semaphore not locked               */
	    public const UInt32 ERROR_CODE_GET_DRIVER_HANDLE 		= 0x460F1A8E;   /* Driver processing completed erroneously.            */
	    public const UInt32 ERROR_CODE_SEND_MSG 				= 0x450E1AC1;   /* Failure to get driver file handle                   */
	    public const UInt32 ERROR_CODE_RECV_MSG 				= 0x450E1AC2;   /* Message sending error                               */
	    public const UInt32 ERROR_CODE_INVALID_RESPONSE 		= 0x450E1AC3;   /* Message receiving error                             */
	    public const UInt32 ERROR_CODE_INVALID_ID 				= 0x450E1AC4;   /* Receiving packet illegal                            */
	    public const UInt32 ERROR_CODE_INVALID_STATUS 			= 0x450E1AC5;   /* Receiving packet ID illegal                         */
	    public const UInt32 ERROR_CODE_INVALID_CMDCODE 			= 0x450E1AC6;   /* Receiving packet status illegal                     */
	    public const UInt32 ERROR_CODE_INVALID_SEQNO 			= 0x450E1AC7;   /* Receiving packet command code illegal               */
	    public const UInt32 ERROR_CODE_SEND_RETRY_OVER 			= 0x450E1AC8;   /* Receiving packet sequence number illegal            */
	    public const UInt32 ERROR_CODE_RECV_RETRY_OVER 			= 0x450E1AC9;   /* Number of retries exceeded (packet sending)         */
	    public const UInt32 ERROR_CODE_RESPONSE_TIMEOUT 		= 0x450E1ACA;   /* Number of retries exceeded (packet receiving)       */
	    public const UInt32 ERROR_CODE_WAIT_FOR_EVENT 			= 0x450E1ACB;   /* Response waiting timeout error                      */
	    public const UInt32 ERROR_CODE_EVENT_OPEN 				= 0x450E1ACC;   /* Event waiting error                                 */
	    public const UInt32 ERROR_CODE_EVENT_RESET 				= 0x450E1ACD;   /* Failure to open event                               */
	    public const UInt32 ERROR_CODE_EVENT_READY 				= 0x450E1ACE;   /* Failure to reset event                              */
	    public const UInt32 ERROR_CODE_PROCESSNUM 				= 0x43001B01;   /* Failure to prepare for waiting for event            */
	    public const UInt32 ERROR_CODE_GET_PROC_INFO 			= 0x43001B02;   /* Number of processes exceeded                        */
	    public const UInt32 ERROR_CODE_THREADNUM 				= 0x43001B03;   /* Process information getting error                   */
	    public const UInt32 ERROR_CODE_GET_THRD_INFO 			= 0x43001B04;   /* Number of threads exceeded                          */
	    public const UInt32 ERROR_CODE_CREATE_MBOX 				= 0x43001B05;   /* Thread information getting error                    */
	    public const UInt32 ERROR_CODE_DELETE_MBOX 				= 0x43001B06;   /* Mail box creation error                             */
	    public const UInt32 ERROR_CODE_GET_TASKID 				= 0x83001B07;   /* Mail box deletion error                             */
	    public const UInt32 ERROR_CODE_NO_THREADINFO 			= 0x43001B08;   /* Failure to get task ID                              */
	    public const UInt32 ERROR_CODE_COM_INITIALIZE 			= 0x43001B09;   /* Specified thread information does not exist.        */
	    public const UInt32 ERROR_CODE_COMDEVICENUM 			= 0x430F1B41;   /* COM initialization error                            */
	    public const UInt32 ERROR_CODE_GET_COM_DEVICE_HANDLE 	= 0x430F1B42;   /* Number of ComDevice exceeded                        */
	    public const UInt32 ERROR_CODE_COM_DEVICE_FULL 			= 0x430F1B43;   /* Failure to get ComDevice information structure      */
	    public const UInt32 ERROR_CODE_CREATE_PANELOBJ 			= 0x430F1B44;   /* ComDevice exceeds the maximum number.               */
	    public const UInt32 ERROR_CODE_OPEN_PANELOBJ 			= 0x430F1B45;   /* Failure to create panel command object              */
	    public const UInt32 ERROR_CODE_CLOSE_PANELOBJ 			= 0x430F1B46;   /* Failure to open panel command object                */
	    public const UInt32 ERROR_CODE_PROC_PANELOBJ 			= 0x430F1B47;   /* Failure to close panel command object               */
	    public const UInt32 ERROR_CODE_CREATE_CNTROBJ 			= 0x430F1B48;   /* Failure to process panel command object             */
	    public const UInt32 ERROR_CODE_OPEN_CNTROBJ 			= 0x430F1B49;   /* Failure to create panel command object              */
	    public const UInt32 ERROR_CODE_CLOSE_CNTROBJ 			= 0x430F1B4A;   /* Failure to open panel command object                */
	    public const UInt32 ERROR_CODE_PROC_CNTROBJ 			= 0x430F1B4B;   /* Failure to close panel command object               */
	    public const UInt32 ERROR_CODE_CREATE_COMDEV_MUTEX 		= 0x430F1B4C;   /* Failure to process panel command object             */
	    public const UInt32 ERROR_CODE_CREATE_COMDEV_MAPFILE 	= 0x430F1B4D;   /* Failure to create Mutex for ComDevice table         */
	    public const UInt32 ERROR_CODE_OPEN_COMDEV_MAPFILE 		= 0x430F1B4E;   /* Failure to create MapFile for ComDevice table       */
	    public const UInt32 ERROR_CODE_NOT_OBJECT_TYPE 			= 0x430F1B4F;   /* Failure to open MapFile for ComDevice table         */
	    public const UInt32 ERROR_CODE_COM_NOT_OPENED 			= 0x430F1B50;   /* Object type error                                   */
	    public const UInt32 ERROR_CODE_PNLCMD_CPU_CONTROL 		= 0x43081B80;   /* Not opened                                          */
	    public const UInt32 ERROR_CODE_PNLCMD_SFILE_READ 		= 0x43081B81;   /* CPU control error                                   */
	    public const UInt32 ERROR_CODE_PNLCMD_SFILE_WRITE 		= 0x43081B82;   /* Failure to read out source file                     */
	    public const UInt32 ERROR_CODE_PNLCMD_REGISTER_READ 	= 0x43081B83;   /* Failure to write in source file                     */
	    public const UInt32 ERROR_CODE_PNLCMD_REGISTER_WRITE 	= 0x43081B84;   /* Failure to read out register                        */
	    public const UInt32 ERROR_CODE_PNLCMD_API_SEND 			= 0x43081B85;   /* Failure to write in register                        */
	    public const UInt32 ERROR_CODE_PNLCMD_API_RECV 			= 0x43081B86;   /* API Send command error                              */
	    public const UInt32 ERROR_CODE_PNLCMD_NO_RESPONSE 		= 0x43081B87;   /* API Recv command error                              */
	    public const UInt32 ERROR_CODE_PNLCMD_PACKET_READ 		= 0x43081B88;   /* No response packet is received at API Recv.         */
	    public const UInt32 ERROR_CODE_PNLCMD_PACKET_WRITE 		= 0x43081B89;   /* Failure to read packet                              */
	    public const UInt32 ERROR_CODE_PNLCMD_STATUS_READ 		= 0x43081B8A;   /* Failure to write packet                             */
	    public const UInt32 ERROR_CODE_NOT_CONTROLLER_RDY 		= 0x440D1BA0;   /*                                                     */
	    public const UInt32 ERROR_CODE_DOUBLE_CMD      			= 0x440D1BA1;   /*                                                     */
	    public const UInt32 ERROR_CODE_DOUBLE_RCMD      		= 0x440D1BA2;   /*                                                     */
	    public const UInt32 ERROR_CODE_FILE_NOT_OPENED 			= 0x43001BC1;   /* Failure to read status                              */
	    public const UInt32 ERROR_CODE_OPENFILE_NUM 			= 0x43001BC2;   /* File is not opened.                                 */
	    public const UInt32 MP_CTRL_SYS_ERROR					= 0x4308106f;   /*                                                     */
	    public const UInt32 MP_CTRL_PARAM_ERR					= 0x43081092;   /*                                                     */
		public const UInt32 MP_CTRL_FILE_NOT_FOUND				= 0x43081094;   /*                                                     */
	    public const UInt32 MP_NOTMOVEHANDLE 					= 0x470B1100;   /* Undefined Move handle                               */
	    public const UInt32 MP_NOTTIMERHANDLE 					= 0x470B1101;   /* Undefined timer handle                              */
	    public const UInt32 MP_NOTINTERRUPT 					= 0x470B1102;   /* Undefined virtual interruption number               */
	    public const UInt32 MP_NOTEVENTHANDLE 					= 0x470B1103;   /* Undefined event handle                              */
	    public const UInt32 MP_NOTMESSAGEHANDLE 				= 0x470B1104;   /* Undefined message handle                            */
	    public const UInt32 MP_NOTUSERFUNCTIONHANDLE 			= 0x470B1105;   /* Undefined user function handle                      */
	    public const UInt32 MP_NOTACTIONHANDLE 					= 0x470B1106;   /* Undefined action handle                             */
	    public const UInt32 MP_NOTSUBSCRIBEHANDLE 				= 0x470B1107;   /* Undefined Subscribe handle                          */
	    public const UInt32 MP_NOTDEVICEHANDLE 					= 0x470B1108;   /* Undefined device handle                             */
	    public const UInt32 MP_NOTAXISHANDLE 					= 0x470B1109;   /* Undefined axis handle                               */
	    public const UInt32 MP_NOTMOVELISTHANDLE 				= 0x470B110A;   /* Undefined MoveList handle                           */
	    public const UInt32 MP_NOTTRACEHANDLE 					= 0x470B110B;   /* Undefined Trace handle                              */
	    public const UInt32 MP_NOTGLOBALDATAHANDLE 				= 0x470B110C;   /* Undefined global data handle                        */
	    public const UInt32 MP_NOTSUPERPOSEHANDLE 				= 0x470B110D;   /* Undefined Superpose handle                          */
	    public const UInt32 MP_NOTCONTROLLERHANDLE 				= 0x470B110E;   /* Undefined Controller handle                         */
	    public const UInt32 MP_NOTFILEHANDLE 					= 0x470B110F;   /* Undefined file handle                               */
	    public const UInt32 MP_NOTREGISTERDATAHANDLE 			= 0x470B1110;   /* Undefined register handle                           */
	    public const UInt32 MP_NOTALARMHANDLE 					= 0x470B1111;   /* Undefined alarm handle                              */
	    public const UInt32 MP_NOTCAMHANDLE 					= 0x470B1112;   /* Undefined CAM handle                                */
	    public const UInt32 MP_NOTHANDLE 						= 0x470B11FF;   /* Undefined handle                                    */
	    public const UInt32 MP_NOTEVENTTYPE 					= 0x470B1200;   /* Undefined event type                                */
	    public const UInt32 MP_NOTDEVICETYPE 					= 0x470B1201;   /* Undefined device type                               */
	    public const UInt32 MP_NOTDATAUNITSIZE 					= 0x4B0B1202;   /* Undefined unit data size                            */
	    public const UInt32 MP_NOTDEVICE 						= 0x470B1203;   /* Undefined device                                    */
	    public const UInt32 MP_NOTACTIONTYPE 					= 0x470B1204;   /* Undefined action type                               */
	    public const UInt32 MP_NOTPARAMNAME 					= 0x4B0B1205;   /* Undefined parameter name                            */
	    public const UInt32 MP_NOTDATATYPE 						= 0x470B1206;   /* Undefined data type                                 */
	    public const UInt32 MP_NOTBUFFERTYPE 					= 0x470B1207;   /* Undefined buffer type                               */
	    public const UInt32 MP_NOTMOVETYPE 						= 0x4B0B1208;   /* Undefined Move type                                 */
	    public const UInt32 MP_NOTANGLETYPE 					= 0x470B1209;   /* Undefined Angle type                                */
	    public const UInt32 MP_NOTDIRECTION 					= 0x4B0B120A;   /* Undefined rotating direction                        */
	    public const UInt32 MP_NOTAXISTYPE 						= 0x4B0B120B;   /* Undefined axis type                                 */
	    public const UInt32 MP_NOTUNITTYPE 						= 0x4B0B120C;   /* Undefined unit type                                 */
	    public const UInt32 MP_NOTCOMDEVICETYPE 				= 0x470B120D;   /* Undefined ComDevice type                            */
	    public const UInt32 MP_NOTCONTROLTYPE 					= 0x470B120E;   /* Undefined Control type                              */
	    public const UInt32 MP_NOTFILETYPE 						= 0x4B0B120F;   /* Undefined file type                                 */
	    public const UInt32 MP_NOTSEMAPHORETYPE 				= 0x470B1210;   /* Undefined semaphore type                            */
	    public const UInt32 MP_NOTSYSTEMOPTION 					= 0x470B1211;   /* Undefined system option                             */
	    public const UInt32 MP_TIMEOUT_ERR 						= 0x470B1212;   /* Timeout error                                       */
	    public const UInt32 MP_TIMEOUT 							= 0x470B1213;   /* Timeout                                             */
	    public const UInt32 MP_NOTSUBSCRIBETYPE 				= 0x470B1214;   /* Undefined scan type                                 */
	    public const UInt32 MP_NOTSCANTYPE 						= 0x4B0B1214;   /* Undefined scan type                                 */
	    public const UInt32 MP_DEVICEOFFSETOVER 				= 0x470B1300;   /* Out-of-range device offset                          */
	    public const UInt32 MP_DEVICEBITOFFSETOVER 				= 0x470B1301;   /* Out-of-range bit offset                             */
	    public const UInt32 MP_UNITCOUNTOVER 					= 0x4B0B1302;   /* Out-of-range quantity                               */
	    public const UInt32 MP_COMPAREVALUEOVER 				= 0x4B0B1303;   /* Out-of-range compared value                         */
	    public const UInt32 MP_FCOMPAREVALUEOVER 				= 0x4B0B1304;   /* Out-of-range floating-point compared value          */
	    public const UInt32 MP_EVENTCOUNTOVER 					= 0x470B1305;   /* Out-of-range virtual interruption number            */
	    public const UInt32 MP_VALUEOVER 						= 0x470B1306;   /* Out-of-range value                                  */
	    public const UInt32 MP_FVALUEOVER 						= 0x470B1307;   /* Out-of-range floating point                         */
	    public const UInt32 MP_PSTOREDVALUEOVER 				= 0x470B1308;   /* Out-of-range storage position pointer               */
	    public const UInt32 MP_PSTOREDFVALUEOVER 				= 0x470B1309;   /* Out-of-range storage position pointer (floating decimal point value)    */
	    public const UInt32 MP_SIZEOVER 						= 0x470B130A;   /* Out-of-range size                                   */
	    public const UInt32 MP_RECEIVETIMEROVER 				= 0x470B1310;   /* Out-of-range waiting time value for receiving       */
	    public const UInt32 MP_RECNUMOVER 						= 0x470B1311;   /* Out-of-range number of records (MoveList)           */
	    public const UInt32 MP_PARAMOVER 						= 0x4B0B1312;   /* Out-of-range parameter                              */
	    public const UInt32 MP_FRAMEOVER 						= 0x470B1313;   /* Out-of-range number of frames                       */
	    public const UInt32 MP_RADIUSOVER 						= 0x4B0B1314;   /* Out-of-range radius                                 */
	    public const UInt32 MP_CONTROLLERNOOVER 				= 0x470B1315;   /* Out-of-range device number                          */
	    public const UInt32 MP_AXISNUMOVER 						= 0x4B0B1316;   /* Out-of-range number of axes                         */
	    public const UInt32 MP_DIGITOVER 						= 0x4B0B1317;   /* Out-of-range number of digits                       */
	    public const UInt32 MP_CALENDARVALUEOVER 				= 0x4B0B1318;   /* Out-of-range calendar data                          */
	    public const UInt32 MP_OFFSETOVER 						= 0x470B1319;   /* Out-of-range offset                                 */
	    public const UInt32 MP_NUMBEROVER 						= 0x470B131A;   /* Out-of-range number of registers has been specified.*/
	    public const UInt32 MP_RACKOVER 						= 0x470B131B;   /* Out-of-range rack number has been specified.        */
	    public const UInt32 MP_SLOTOVER 						= 0x470B131C;   /* Out-of-range slot number has been specified.        */
	    public const UInt32 MP_FIXVALUEOVER 					= 0x470B131D;   /* Fixed decimal point type data has been out of range.*/
        public const UInt32 MP_REGISTERINFOROVER                = 0x470B131E;	/* Out-of-range number of register infomation has been specified.*/
	    public const UInt32 PC_MEMORY_ERR 						= 0x430B1400;   /* PC memory shortage                                  */
	    public const UInt32 MP_NOCOMMUDEVICETYPE 				= 0x470B1500;   /* Communication device type specification error       */
	    public const UInt32 MP_NOTPROTOCOLTYPE 					= 0x470B1501;   /* Invalid protocol type                               */
	    public const UInt32 MP_NOTFUNCMODE 						= 0x470B1502;   /* Invalid function mode                               */
	    public const UInt32 MP_MYADDROVER 						= 0x470B1503;   /* Out-of-range local station address has been set.    */
	    public const UInt32 MP_NOTPORTTYPE 						= 0x470B1504;   /* Invalid port type                                   */
	    public const UInt32 MP_NOTPROTMODE 						= 0x470B1505;   /* Invalid protocol mode                               */
	    public const UInt32 MP_NOTCHARSIZE 						= 0x470B1506;   /* Invalid character bit length                        */
	    public const UInt32 MP_NOTPARITYBIT 					= 0x470B1507;   /* Invalid parity bit                                  */
	    public const UInt32 MP_NOTSTOPBIT 						= 0x470B1508;   /* Invalid stop bit                                    */
	    public const UInt32 MP_NOTBAUDRAT 						= 0x470B1509;   /* Invalid transmission speed                          */
	    public const UInt32 MP_TRANSDELAYOVER 					= 0x470B1510;   /* Out-of-range sending delay has been specified.      */
	    public const UInt32 MP_PEERADDROVER 					= 0x470B1511;   /* Out-of-range remote station address has been specified. */
	    public const UInt32 MP_SUBNETMASKOVER 					= 0x470B1512;   /* Out-of-range subnet mask has been specified.        */
	    public const UInt32 MP_GWADDROVER 						= 0x470B1513;   /* Out-of-range GW address has been specified.         */
	    public const UInt32 MP_DIAGPORTOVER 					= 0x470B1514;   /* Out-of-range diagnostic port has been specified.    */
	    public const UInt32 MP_PROCRETRYOVER 					= 0x470B1515;   /* Out-of-range number of retries has been specified.  */
	    public const UInt32 MP_TCPZEROWINOVER 					= 0x470B1516;   /* Out-of-range TCP zero window timer                  */
	    public const UInt32 MP_TCPRETRYOVER 					= 0x470B1517;   /* Out-of-range TCP resending timer value              */
	    public const UInt32 MP_TCPFINOVER 						= 0x470B1518;   /* Out-of-range completion timer value                 */
	    public const UInt32 MP_IPASSEMBLEOVER 					= 0x470B1519;   /* Out-of-range IP incorporating timer value           */
	    public const UInt32 MP_MAXPKTLENOVER 					= 0x470B1520;   /* Out-of-range maximum packet length                  */
	    public const UInt32 MP_PEERPORTOVER 					= 0x470B1521;   /* Out-of-range remote station port                    */
	    public const UInt32 MP_MYPORTOVER 						= 0x470B1522;   /* Out-of-range local station port                     */
	    public const UInt32 MP_NOTTRANSPROT 					= 0x470B1523;   /* Invalid transport layer protocol                    */
	    public const UInt32 MP_NOTAPPROT 						= 0x470B1524;   /* Invalid application layer protocol                  */
	    public const UInt32 MP_NOTCODETYPE 						= 0x470B1525;   /* Invalid code type                                   */
	    public const UInt32 MP_CYCTIMOVER 						= 0x470B1526;   /* Out-of-range communication cycle has been specified.*/
	    public const UInt32 MP_NOTIOMAPCOM 						= 0x470B1527;   /* Invalid I/O commands                                */
	    public const UInt32 MP_NOTIOTYPE 						= 0x470B1528;   /* Invalid I/O type specification                      */
	    public const UInt32 MP_IOOFFSETOVER 					= 0x470B1529;   /* Out-of-range I/O offset has been allocated.         */
	    public const UInt32 MP_IOSIZEOVER 						= 0x470B1530;   /* Out-of-range I/O size has been allocated (individualy). */
	    public const UInt32 MP_TIOSIZEOVER 						= 0x470B1531;   /* Out-of-range I/O size has been allocated (total).   */
	    public const UInt32 MP_MEMORY_ERR 						= 0x470B1532;   /* Controller memory shortage                          */
	    public const UInt32 MP_NOTPTR 							= 0x470B1533;   /* Invalid pointer (communication device specification structure/device inherent information/pointer error to objective communication device handle)   */
	    public const UInt32 MP_TABLEOVER 						= 0x43001800;   /* Event detection table resource cannot be got.       */
	    public const UInt32 MP_ALARM 							= 0x43001801;   /* Alarm has occurred.                                 */
	    public const UInt32 MP_MEMORYOVER 						= 0x43001802;   /* Memory resource cannot be got.                      */
	    public const UInt32 MP_EXEC_ERR 						= 0x470B1803;   /* System execution error                              */
	    public const UInt32 MP_NOTLOGICALAXIS 					= 0x470B1804;   /* Logical axis number error                           */
	    public const UInt32 MP_NOTSUPPORTED 					= 0x470B1805;   /* Not supported                                       */
	    public const UInt32 MP_ILLTEXT 							= 0x470B1806;   /* Out-of-range length of character string was input.  */
	    public const UInt32 MP_NOFILENAME 						= 0x470B1807;   /* File name has not been set.                         */
	    public const UInt32 MP_NOTREGSTERNAME 					= 0x470B1808;   /* Specified register data name cannot be found.       */
	    public const UInt32 MP_FILEALREADYOPEN 					= 0x4B0B1809;   /* The same file has already been opened.              */
	    public const UInt32 MP_NOFILEPACKET 					= 0x470B180A;   /* Specified source file packet cannot be found.       */
	    public const UInt32 MP_NOTFILEPACKETSIZE 				= 0x470B180B;   /* Source file packet size is incorrect.               */
	    public const UInt32 MP_NOTUSERFUNCTION 					= 0x4B0B180C;   /* Specified user funtion does not exist.              */
	    public const UInt32 MP_NOTPARAMETERTYPE 				= 0x4B0B180D;   /* Specified parameter type does not exist.            */
	    public const UInt32 MP_ILLREGHANDLETYPE 				= 0x470B180E;   /* Erroneous register handle type specified.           */
	    public const UInt32 MP_ILLREGTYPE 						= 0x470B1810;   /* Erroneous register type specified.                  */
	    public const UInt32 MP_ILLREGSIZE 						= 0x470B1811;   /* Erroneous register size specified.(other than WORD) */
	    public const UInt32 MP_REGNUMOVER 						= 0x470B1812;   /* Out-of-range register                               */
	    public const UInt32 MP_RELEASEWAIT 						= 0x470B1813;   /* Waiting status released                             */
	    public const UInt32 MP_PRIORITYOVER 					= 0x470B1814;   /* Priority that can not be set                        */
	    public const UInt32 MP_NOTCHANGEPRIORITY 				= 0x470B1815;   /* Priority that cannot be changed                     */
	    public const UInt32 MP_SEMAPHOREOVER 					= 0x470B1816;   /* Semaphore definition over                           */
	    public const UInt32 MP_NOTSEMAPHOREHANDLE 				= 0x470B1817;   /* Undefined semaphore handle specification            */
	    public const UInt32 MP_SEMAPHORELOCKED 					= 0x470B1818;   /* Specified semaphore handle being locked             */
	    public const UInt32 MP_CONTINUE_RELEASEWAIT 			= 0x470B1819;   /* Waiting status released during ymcContinueWaitForCompletion */
	    public const UInt32 MP_NOTTABLENAME 					= 0x4B0B1820;   /* Undefined Table name                                */
	    public const UInt32 MP_ILLTABLETYPE 					= 0x470B1821;   /* Illegal Table Type                                  */
	    public const UInt32 MP_TIMEOUTVALUEOVER 				= 0x470B1822;   /* Out-of-range timeout value has been specified       */
	    public const UInt32 MP_OTHER_ERR 						= 0x470B19FF;   /* Other errors                                        */
	}
}